name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy_gh_pages:
    runs-on: "ubuntu-latest"

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install and build
        run: cd solid && make build

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./solid/build
          cname: playground.writebetacode.com
